### ISSUE TITLE
Unable to start server in production mode

### ISSUE THREAD

**Issue by tranquochuy** [richardkall/react-starter#1]
I run npm start but it came this error

```
module.js:328
    throw err;
    ^

Error: Cannot find module 'history/lib/createLocation'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (reactMiddleware.js:10:25)
    at Module._compile (module.js:410:26)
    at loader (/Users/huytran/training/react/react-starter/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/huytran/training/react/react-starter/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

**Comment by richardkall** [comment]
I just tried on a fresh install and I can't reproduce this. Which Node.js version are you using? The history module is a [dependency to react-router](https://github.com/reactjs/react-router/blob/master/package.json#L38) so it should be fine.

**Comment by tranquochuy** [comment]
@richardkall I'm using Node.js 4.2.6. My react-router version is "react-router": "~2.0.0"

**Comment by richardkall** [comment]
Ah, I see what the problem is. npm 3 uses a [flat dependency tree](https://docs.npmjs.com/how-npm-works/npm3) while npm 2 is nested. I'll add `history` and `babel-register` to package.json and fix this issue.

Thanks for reporting this!
