### ISSUE TITLE
Cannot read property 'createHref' of undefined

### ISSUE THREAD

**Issue by ppazuchowski** [richardkall/react-starter#13]
Hi, 
thanks for your interesting boilerplate.
I have a issue.

I have downloaded your repository from master branch, and after npm install && npm run dev server has started but when I open url http://127.0.0.1:3000 error appears.

Do you have also this error? Can you help me?
Ive attached error stack:

Cannot read property 'createHref' of undefined

TypeError: Cannot read property 'createHref' of undefined
   at Link.render (src\node_modules\react-router-dom\Link.js:72:35)
   at src\node_modules\react-dom\lib\ReactCompositeComponent.js:796:21
   at measureLifeCyclePerf (src\node_modules\react-dom\lib\ReactCompositeComponent.js:75:12)
   at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (src\node_modules\react-dom\lib\ReactCompositeComponent.js:795:25)
   at ReactCompositeComponentWrapper._renderValidatedComponent (src\node_modules\react-dom\lib\ReactCompositeComponent.js:822:32)
   at ReactCompositeComponentWrapper.performInitialMount (src\node_modules\react-dom\lib\ReactCompositeComponent.js:362:30)
   at ReactCompositeComponentWrapper.mountComponent (src\node_modules\react-dom\lib\ReactCompositeComponent.js:258:21)
   at Object.mountComponent (src\node_modules\react-dom\lib\ReactReconciler.js:46:35)
   at ReactDOMComponent.mountChildren (src\node_modules\react-dom\lib\ReactMultiChild.js:238:44)
   at ReactDOMComponent._createContentMarkup (src\node_modules\react-dom\lib\ReactDOMComponent.js:653:32)

**Comment by richardkall** [comment]
Thanks @ppazuchowski, looking into this! A problem for me as well when I remove all node_modules.

**Comment by richardkall** [comment]
It should be fixed now @ppazuchowski. Let me know if you have any more issues..
