### ISSUE TITLE
Error: Cannot find module '../../../build/assets.json'

### ISSUE THREAD

**Issue by grigio** [richardkall/react-starter#6]
it seems that `npm run start` is required before `npm run start-dev`

```
❯ npm run start-dev                                                                                                                      ⏎

> react-starter@0.0.0 start-dev /Users/grigio/+persistant/Code/hn-search-notify-react
> nodemon server -w server

[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/grigio/+persistant/Code/hn-search-notify-react/server/**/*
[nodemon] starting `node server`
module.js:341
    throw err;
    ^

Error: Cannot find module '../../../build/assets.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (renderApp.js:11:1)
    at Module._compile (module.js:413:34)
    at loader (/Users/grigio/+persistant/Code/hn-search-notify-react/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/grigio/+persistant/Code/hn-search-notify-react/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by richardkall** [comment]
@grigio Thanks for reporting this! It should be fixed now.
